package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Aporte generated by hbm2java
 */
public class Aporte  implements java.io.Serializable {


     private Integer id;
     private Cuentaahorro cuentaahorro;
     private double monto;
     private Date fecha;

    public Aporte() {
    }

    public Aporte(Cuentaahorro cuentaahorro, double monto, Date fecha) {
       this.cuentaahorro = cuentaahorro;
       this.monto = monto;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cuentaahorro getCuentaahorro() {
        return this.cuentaahorro;
    }
    
    public void setCuentaahorro(Cuentaahorro cuentaahorro) {
        this.cuentaahorro = cuentaahorro;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


