package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bobeda generated by hbm2java
 */
public class Bobeda  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private double montoApertura;
     private double montoCierre;
     private Date fechaApertura;
     private Date fechaCierre;
     private String moneda;
     private int idEstado;
     private Set transferencias = new HashSet(0);
     private Set detallesaldobobedas = new HashSet(0);

    public Bobeda() {
    }

	
    public Bobeda(String nombre, double montoApertura, double montoCierre, Date fechaApertura, String moneda, int idEstado) {
        this.nombre = nombre;
        this.montoApertura = montoApertura;
        this.montoCierre = montoCierre;
        this.fechaApertura = fechaApertura;
        this.moneda = moneda;
        this.idEstado = idEstado;
    }
    public Bobeda(String nombre, double montoApertura, double montoCierre, Date fechaApertura, Date fechaCierre, String moneda, int idEstado, Set transferencias, Set detallesaldobobedas) {
       this.nombre = nombre;
       this.montoApertura = montoApertura;
       this.montoCierre = montoCierre;
       this.fechaApertura = fechaApertura;
       this.fechaCierre = fechaCierre;
       this.moneda = moneda;
       this.idEstado = idEstado;
       this.transferencias = transferencias;
       this.detallesaldobobedas = detallesaldobobedas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getMontoApertura() {
        return this.montoApertura;
    }
    
    public void setMontoApertura(double montoApertura) {
        this.montoApertura = montoApertura;
    }
    public double getMontoCierre() {
        return this.montoCierre;
    }
    
    public void setMontoCierre(double montoCierre) {
        this.montoCierre = montoCierre;
    }
    public Date getFechaApertura() {
        return this.fechaApertura;
    }
    
    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }
    public Date getFechaCierre() {
        return this.fechaCierre;
    }
    
    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public Set getTransferencias() {
        return this.transferencias;
    }
    
    public void setTransferencias(Set transferencias) {
        this.transferencias = transferencias;
    }
    public Set getDetallesaldobobedas() {
        return this.detallesaldobobedas;
    }
    
    public void setDetallesaldobobedas(Set detallesaldobobedas) {
        this.detallesaldobobedas = detallesaldobobedas;
    }




}


