package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Cajero generated by hbm2java
 */
public class Cajero implements java.io.Serializable {

    private Integer id;
    private Caja caja;
    private Usuario usuario;
    private double saldoApertura;
    private double saldoCierre;
    private Date fechaApertura;
    private Date fechaCierre;
    private boolean cerrado;
    private int idEstado;

    public Cajero() {
    }

    public Cajero(Caja caja, Usuario usuario, double saldoApertura, double saldoCierre, Date fechaApertura, boolean cerrado, int idEstado) {
        this.caja = caja;
        this.usuario = usuario;
        this.saldoApertura = saldoApertura;
        this.saldoCierre = saldoCierre;
        this.fechaApertura = fechaApertura;
        this.cerrado = cerrado;
        this.idEstado = idEstado;
    }

    public Cajero(Caja caja, Usuario usuario, double saldoApertura, double saldoCierre, Date fechaApertura, Date fechaCierre, boolean cerrado, int idEstado) {
        this.caja = caja;
        this.usuario = usuario;
        this.saldoApertura = saldoApertura;
        this.saldoCierre = saldoCierre;
        this.fechaApertura = fechaApertura;
        this.fechaCierre = fechaCierre;
        this.cerrado = cerrado;
        this.idEstado = idEstado;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Caja getCaja() {
        return this.caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public double getSaldoApertura() {
        return this.saldoApertura;
    }

    public void setSaldoApertura(double saldoApertura) {
        this.saldoApertura = saldoApertura;
    }

    public double getSaldoCierre() {
        return this.saldoCierre;
    }

    public void setSaldoCierre(double saldoCierre) {
        this.saldoCierre = saldoCierre;
    }

    public Date getFechaApertura() {
        return this.fechaApertura;
    }

    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    public Date getFechaCierre() {
        return this.fechaCierre;
    }

    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }

    public boolean isCerrado() {
        return this.cerrado;
    }

    public void setCerrado(boolean cerrado) {
        this.cerrado = cerrado;
    }

    public int getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
}
