package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Comprobante generated by hbm2java
 */
public class Comprobante implements java.io.Serializable {

    private Integer id;
    private Agencia agencia;
    private Cliente cliente;
    private Naturalezacomprobante naturalezacomprobante;
    private Usuario usuario;
    private Date fecha;
    private String moneda;
    private double monto;
    private String observaciones;
    private String glosa;
    private int idEstado;

    public Comprobante() {
    }

    public Comprobante(Agencia agencia, Cliente cliente, Naturalezacomprobante naturalezacomprobante, Usuario usuario, Date fecha, String moneda, double monto, String glosa, int idEstado) {
        this.agencia = agencia;
        this.cliente = cliente;
        this.naturalezacomprobante = naturalezacomprobante;
        this.usuario = usuario;
        this.fecha = fecha;
        this.moneda = moneda;
        this.monto = monto;
        this.glosa = glosa;
        this.idEstado = idEstado;
    }

    public Comprobante(Agencia agencia, Cliente cliente, Naturalezacomprobante naturalezacomprobante, Usuario usuario, Date fecha, String moneda, double monto, String observaciones, String glosa, int idEstado) {
        this.agencia = agencia;
        this.cliente = cliente;
        this.naturalezacomprobante = naturalezacomprobante;
        this.usuario = usuario;
        this.fecha = fecha;
        this.moneda = moneda;
        this.monto = monto;
        this.observaciones = observaciones;
        this.glosa = glosa;
        this.idEstado = idEstado;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Agencia getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Naturalezacomprobante getNaturalezacomprobante() {
        return this.naturalezacomprobante;
    }

    public void setNaturalezacomprobante(Naturalezacomprobante naturalezacomprobante) {
        this.naturalezacomprobante = naturalezacomprobante;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getMoneda() {
        return this.moneda;
    }

    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    public double getMonto() {
        return this.monto;
    }

    public void setMonto(double monto) {
        this.monto = monto;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getGlosa() {
        return this.glosa;
    }

    public void setGlosa(String glosa) {
        this.glosa = glosa;
    }

    public int getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
}
