package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Conyugue generated by hbm2java
 */
public class Conyugue implements java.io.Serializable {

    private Integer id;
    private String dni;
    private String nombre;
    private String apellidoPat;
    private String apellidoMat;
    private Integer numeroHijos;
    private Integer numeroDependientes;
    private String profesion;

    public Conyugue() {
    }

    public Conyugue(String dni, String nombre, String apellidoPat, String apellidoMat) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
    }

    public Conyugue(String dni, String nombre, String apellidoPat, String apellidoMat, Integer numeroHijos, Integer numeroDependientes, String profesion) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.numeroHijos = numeroHijos;
        this.numeroDependientes = numeroDependientes;
        this.profesion = profesion;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidoPat() {
        return this.apellidoPat;
    }

    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }

    public String getApellidoMat() {
        return this.apellidoMat;
    }

    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }

    public Integer getNumeroHijos() {
        return this.numeroHijos;
    }

    public void setNumeroHijos(Integer numeroHijos) {
        this.numeroHijos = numeroHijos;
    }

    public Integer getNumeroDependientes() {
        return this.numeroDependientes;
    }

    public void setNumeroDependientes(Integer numeroDependientes) {
        this.numeroDependientes = numeroDependientes;
    }

    public String getProfesion() {
        return this.profesion;
    }

    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }

}
