package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Cuentacredito generated by hbm2java
 */
public class Cuentacredito implements java.io.Serializable {

    private Integer id;
    private Calendario calendario;
    private Cliente cliente;
    private Estadocredito estadocredito;
    private Frecuenciapago frecuenciapago;
    private Productocredito productocredito;
    private String cuentaCredito;
    private String moneda;
    private double importeCredito;
    private double interes;
    private int plazo;
    private double tasaInteres;
    private double tasaInteresmora;
    private int periodoGracia;
    private int plazoPagoCuotas;
    private Date fechaApertura;
    private Date fechaVencimiento;
    private double centralRiesgo;
    private double gastosAdministrativo;
    private double seguroDesgravamen;
    private double encaje;
    private double montoDesembolso;
    private String mensaje;
    private String garante;

    public Cuentacredito() {
    }

    public Cuentacredito(Calendario calendario, Cliente cliente, Estadocredito estadocredito, Frecuenciapago frecuenciapago, Productocredito productocredito, String cuentaCredito, String moneda, double importeCredito, double interes, int plazo, double tasaInteres, double tasaInteresmora, int periodoGracia, int plazoPagoCuotas, Date fechaApertura, Date fechaVencimiento, double centralRiesgo, double gastosAdministrativo, double seguroDesgravamen, double encaje, double montoDesembolso) {
        this.calendario = calendario;
        this.cliente = cliente;
        this.estadocredito = estadocredito;
        this.frecuenciapago = frecuenciapago;
        this.productocredito = productocredito;
        this.cuentaCredito = cuentaCredito;
        this.moneda = moneda;
        this.importeCredito = importeCredito;
        this.interes = interes;
        this.plazo = plazo;
        this.tasaInteres = tasaInteres;
        this.tasaInteresmora = tasaInteresmora;
        this.periodoGracia = periodoGracia;
        this.plazoPagoCuotas = plazoPagoCuotas;
        this.fechaApertura = fechaApertura;
        this.fechaVencimiento = fechaVencimiento;
        this.centralRiesgo = centralRiesgo;
        this.gastosAdministrativo = gastosAdministrativo;
        this.seguroDesgravamen = seguroDesgravamen;
        this.encaje = encaje;
        this.montoDesembolso = montoDesembolso;
    }

    public Cuentacredito(Calendario calendario, Cliente cliente, Estadocredito estadocredito, Frecuenciapago frecuenciapago, Productocredito productocredito, String cuentaCredito, String moneda, double importeCredito, double interes, int plazo, double tasaInteres, double tasaInteresmora, int periodoGracia, int plazoPagoCuotas, Date fechaApertura, Date fechaVencimiento, double centralRiesgo, double gastosAdministrativo, double seguroDesgravamen, double encaje, double montoDesembolso, String mensaje, String garante) {
        this.calendario = calendario;
        this.cliente = cliente;
        this.estadocredito = estadocredito;
        this.frecuenciapago = frecuenciapago;
        this.productocredito = productocredito;
        this.cuentaCredito = cuentaCredito;
        this.moneda = moneda;
        this.importeCredito = importeCredito;
        this.interes = interes;
        this.plazo = plazo;
        this.tasaInteres = tasaInteres;
        this.tasaInteresmora = tasaInteresmora;
        this.periodoGracia = periodoGracia;
        this.plazoPagoCuotas = plazoPagoCuotas;
        this.fechaApertura = fechaApertura;
        this.fechaVencimiento = fechaVencimiento;
        this.centralRiesgo = centralRiesgo;
        this.gastosAdministrativo = gastosAdministrativo;
        this.seguroDesgravamen = seguroDesgravamen;
        this.encaje = encaje;
        this.montoDesembolso = montoDesembolso;
        this.mensaje = mensaje;
        this.garante = garante;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Calendario getCalendario() {
        return this.calendario;
    }

    public void setCalendario(Calendario calendario) {
        this.calendario = calendario;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Estadocredito getEstadocredito() {
        return this.estadocredito;
    }

    public void setEstadocredito(Estadocredito estadocredito) {
        this.estadocredito = estadocredito;
    }

    public Frecuenciapago getFrecuenciapago() {
        return this.frecuenciapago;
    }

    public void setFrecuenciapago(Frecuenciapago frecuenciapago) {
        this.frecuenciapago = frecuenciapago;
    }

    public Productocredito getProductocredito() {
        return this.productocredito;
    }

    public void setProductocredito(Productocredito productocredito) {
        this.productocredito = productocredito;
    }

    public String getCuentaCredito() {
        return this.cuentaCredito;
    }

    public void setCuentaCredito(String cuentaCredito) {
        this.cuentaCredito = cuentaCredito;
    }

    public String getMoneda() {
        return this.moneda;
    }

    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    public double getImporteCredito() {
        return this.importeCredito;
    }

    public void setImporteCredito(double importeCredito) {
        this.importeCredito = importeCredito;
    }

    public double getInteres() {
        return this.interes;
    }

    public void setInteres(double interes) {
        this.interes = interes;
    }

    public int getPlazo() {
        return this.plazo;
    }

    public void setPlazo(int plazo) {
        this.plazo = plazo;
    }

    public double getTasaInteres() {
        return this.tasaInteres;
    }

    public void setTasaInteres(double tasaInteres) {
        this.tasaInteres = tasaInteres;
    }

    public double getTasaInteresmora() {
        return this.tasaInteresmora;
    }

    public void setTasaInteresmora(double tasaInteresmora) {
        this.tasaInteresmora = tasaInteresmora;
    }

    public int getPeriodoGracia() {
        return this.periodoGracia;
    }

    public void setPeriodoGracia(int periodoGracia) {
        this.periodoGracia = periodoGracia;
    }

    public int getPlazoPagoCuotas() {
        return this.plazoPagoCuotas;
    }

    public void setPlazoPagoCuotas(int plazoPagoCuotas) {
        this.plazoPagoCuotas = plazoPagoCuotas;
    }

    public Date getFechaApertura() {
        return this.fechaApertura;
    }

    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    public double getCentralRiesgo() {
        return this.centralRiesgo;
    }

    public void setCentralRiesgo(double centralRiesgo) {
        this.centralRiesgo = centralRiesgo;
    }

    public double getGastosAdministrativo() {
        return this.gastosAdministrativo;
    }

    public void setGastosAdministrativo(double gastosAdministrativo) {
        this.gastosAdministrativo = gastosAdministrativo;
    }

    public double getSeguroDesgravamen() {
        return this.seguroDesgravamen;
    }

    public void setSeguroDesgravamen(double seguroDesgravamen) {
        this.seguroDesgravamen = seguroDesgravamen;
    }

    public double getEncaje() {
        return this.encaje;
    }

    public void setEncaje(double encaje) {
        this.encaje = encaje;
    }

    public double getMontoDesembolso() {
        return this.montoDesembolso;
    }

    public void setMontoDesembolso(double montoDesembolso) {
        this.montoDesembolso = montoDesembolso;
    }

    public String getMensaje() {
        return this.mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    public String getGarante() {
        return this.garante;
    }

    public void setGarante(String garante) {
        this.garante = garante;
    }

}
