package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Desembolso generated by hbm2java
 */
public class Desembolso  implements java.io.Serializable {


     private Integer id;
     private Cuentacredito cuentacredito;
     private Estadodesembolso estadodesembolso;
     private Date fechaVence;
     private Date fechaPago;
     private String diaPago;
     private double cuota;
     private double interes;
     private double amortizacion;
     private double saldoInsoluto;
     private double deudaExtinguida;
     private double cuotac;
     private double mora;
     private double cargos;
     private int diasAtraso;
     private int idEstadomora;

    public Desembolso() {
    }

	
    public Desembolso(Cuentacredito cuentacredito, Estadodesembolso estadodesembolso, Date fechaVence, String diaPago, double cuota, double interes, double amortizacion, double saldoInsoluto, double deudaExtinguida, double cuotac, double mora, double cargos, int diasAtraso, int idEstadomora) {
        this.cuentacredito = cuentacredito;
        this.estadodesembolso = estadodesembolso;
        this.fechaVence = fechaVence;
        this.diaPago = diaPago;
        this.cuota = cuota;
        this.interes = interes;
        this.amortizacion = amortizacion;
        this.saldoInsoluto = saldoInsoluto;
        this.deudaExtinguida = deudaExtinguida;
        this.cuotac = cuotac;
        this.mora = mora;
        this.cargos = cargos;
        this.diasAtraso = diasAtraso;
        this.idEstadomora = idEstadomora;
    }
    public Desembolso(Cuentacredito cuentacredito, Estadodesembolso estadodesembolso, Date fechaVence, Date fechaPago, String diaPago, double cuota, double interes, double amortizacion, double saldoInsoluto, double deudaExtinguida, double cuotac, double mora, double cargos, int diasAtraso, int idEstadomora) {
       this.cuentacredito = cuentacredito;
       this.estadodesembolso = estadodesembolso;
       this.fechaVence = fechaVence;
       this.fechaPago = fechaPago;
       this.diaPago = diaPago;
       this.cuota = cuota;
       this.interes = interes;
       this.amortizacion = amortizacion;
       this.saldoInsoluto = saldoInsoluto;
       this.deudaExtinguida = deudaExtinguida;
       this.cuotac = cuotac;
       this.mora = mora;
       this.cargos = cargos;
       this.diasAtraso = diasAtraso;
       this.idEstadomora = idEstadomora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cuentacredito getCuentacredito() {
        return this.cuentacredito;
    }
    
    public void setCuentacredito(Cuentacredito cuentacredito) {
        this.cuentacredito = cuentacredito;
    }
    public Estadodesembolso getEstadodesembolso() {
        return this.estadodesembolso;
    }
    
    public void setEstadodesembolso(Estadodesembolso estadodesembolso) {
        this.estadodesembolso = estadodesembolso;
    }
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public String getDiaPago() {
        return this.diaPago;
    }
    
    public void setDiaPago(String diaPago) {
        this.diaPago = diaPago;
    }
    public double getCuota() {
        return this.cuota;
    }
    
    public void setCuota(double cuota) {
        this.cuota = cuota;
    }
    public double getInteres() {
        return this.interes;
    }
    
    public void setInteres(double interes) {
        this.interes = interes;
    }
    public double getAmortizacion() {
        return this.amortizacion;
    }
    
    public void setAmortizacion(double amortizacion) {
        this.amortizacion = amortizacion;
    }
    public double getSaldoInsoluto() {
        return this.saldoInsoluto;
    }
    
    public void setSaldoInsoluto(double saldoInsoluto) {
        this.saldoInsoluto = saldoInsoluto;
    }
    public double getDeudaExtinguida() {
        return this.deudaExtinguida;
    }
    
    public void setDeudaExtinguida(double deudaExtinguida) {
        this.deudaExtinguida = deudaExtinguida;
    }
    public double getCuotac() {
        return this.cuotac;
    }
    
    public void setCuotac(double cuotac) {
        this.cuotac = cuotac;
    }
    public double getMora() {
        return this.mora;
    }
    
    public void setMora(double mora) {
        this.mora = mora;
    }
    public double getCargos() {
        return this.cargos;
    }
    
    public void setCargos(double cargos) {
        this.cargos = cargos;
    }
    public int getDiasAtraso() {
        return this.diasAtraso;
    }
    
    public void setDiasAtraso(int diasAtraso) {
        this.diasAtraso = diasAtraso;
    }
    public int getIdEstadomora() {
        return this.idEstadomora;
    }
    
    public void setIdEstadomora(int idEstadomora) {
        this.idEstadomora = idEstadomora;
    }




}


