package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1



/**
 * Detallesaldocajero generated by hbm2java
 */
public class Detallesaldocajero  implements java.io.Serializable {


     private Integer id;
     private Cajero cajero;
     private String denominacion;
     private double valor;
     private int cantidad;
     private double monto;
     private boolean apertura;

    public Detallesaldocajero() {
    }

    public Detallesaldocajero(Cajero cajero, String denominacion, double valor, int cantidad, double monto, boolean apertura) {
       this.cajero = cajero;
       this.denominacion = denominacion;
       this.valor = valor;
       this.cantidad = cantidad;
       this.monto = monto;
       this.apertura = apertura;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cajero getCajero() {
        return this.cajero;
    }
    
    public void setCajero(Cajero cajero) {
        this.cajero = cajero;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public boolean isApertura() {
        return this.apertura;
    }
    
    public void setApertura(boolean apertura) {
        this.apertura = apertura;
    }




}


