package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1



/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private Integer id;
     private Provincia provincia;
     private String nombre;
     private Integer reniec;

    public Distrito() {
    }

	
    public Distrito(Provincia provincia, String nombre) {
        this.provincia = provincia;
        this.nombre = nombre;
    }
    public Distrito(Provincia provincia, String nombre, Integer reniec) {
       this.provincia = provincia;
       this.nombre = nombre;
       this.reniec = reniec;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getReniec() {
        return this.reniec;
    }
    
    public void setReniec(Integer reniec) {
        this.reniec = reniec;
    }




}


