package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

    private Integer id;
    private Agencia agencia;
    private Persona persona;
    private Tipoempleado tipoempleado;
    private Date fechaInicio;

    public Empleado() {
    }

    public Empleado(Agencia agencia, Persona persona, Tipoempleado tipoempleado, Date fechaInicio) {
        this.agencia = agencia;
        this.persona = persona;
        this.tipoempleado = tipoempleado;
        this.fechaInicio = fechaInicio;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Agencia getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Tipoempleado getTipoempleado() {
        return this.tipoempleado;
    }

    public void setTipoempleado(Tipoempleado tipoempleado) {
        this.tipoempleado = tipoempleado;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

}
