package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

/**
 * Estadodesembolso generated by hbm2java
 */
public class Estadodesembolso implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private String sigla;
    private boolean estado;

    public Estadodesembolso() {
    }

    public Estadodesembolso(int id) {
        this.id = id;
    }

    public Estadodesembolso(String nombre, String sigla, boolean estado) {
        this.nombre = nombre;
        this.sigla = sigla;
        this.estado = estado;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getSigla() {
        return this.sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

}
