package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

/**
 * Frecuenciaaporte generated by hbm2java
 */
public class Frecuenciaaporte implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private int dias;
    private boolean estado;

    public Frecuenciaaporte() {
    }

    public Frecuenciaaporte(int id) {
        this.id = id;
    }

    public Frecuenciaaporte(String nombre, int dias, boolean estado) {
        this.nombre = nombre;
        this.dias = dias;
        this.estado = estado;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getDias() {
        return this.dias;
    }

    public void setDias(int dias) {
        this.dias = dias;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

}
