package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Garante generated by hbm2java
 */
public class Garante  implements java.io.Serializable {


     private Integer id;
     private Cuentacredito cuentacredito;
     private int numeroGarante;
     private String descripcion;
     private Date fechaActivacion;
     private Date fechaLevantamiento;
     private double importeGarante;
     private double importeComprometido;
     private double importeLibre;
     private boolean estado;
     private String tipoGarante;
     private String tipoMoneda;

    public Garante() {
    }

    public Garante(Cuentacredito cuentacredito, int numeroGarante, String descripcion, Date fechaActivacion, Date fechaLevantamiento, double importeGarante, double importeComprometido, double importeLibre, boolean estado, String tipoGarante, String tipoMoneda) {
       this.cuentacredito = cuentacredito;
       this.numeroGarante = numeroGarante;
       this.descripcion = descripcion;
       this.fechaActivacion = fechaActivacion;
       this.fechaLevantamiento = fechaLevantamiento;
       this.importeGarante = importeGarante;
       this.importeComprometido = importeComprometido;
       this.importeLibre = importeLibre;
       this.estado = estado;
       this.tipoGarante = tipoGarante;
       this.tipoMoneda = tipoMoneda;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cuentacredito getCuentacredito() {
        return this.cuentacredito;
    }
    
    public void setCuentacredito(Cuentacredito cuentacredito) {
        this.cuentacredito = cuentacredito;
    }
    public int getNumeroGarante() {
        return this.numeroGarante;
    }
    
    public void setNumeroGarante(int numeroGarante) {
        this.numeroGarante = numeroGarante;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaActivacion() {
        return this.fechaActivacion;
    }
    
    public void setFechaActivacion(Date fechaActivacion) {
        this.fechaActivacion = fechaActivacion;
    }
    public Date getFechaLevantamiento() {
        return this.fechaLevantamiento;
    }
    
    public void setFechaLevantamiento(Date fechaLevantamiento) {
        this.fechaLevantamiento = fechaLevantamiento;
    }
    public double getImporteGarante() {
        return this.importeGarante;
    }
    
    public void setImporteGarante(double importeGarante) {
        this.importeGarante = importeGarante;
    }
    public double getImporteComprometido() {
        return this.importeComprometido;
    }
    
    public void setImporteComprometido(double importeComprometido) {
        this.importeComprometido = importeComprometido;
    }
    public double getImporteLibre() {
        return this.importeLibre;
    }
    
    public void setImporteLibre(double importeLibre) {
        this.importeLibre = importeLibre;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getTipoGarante() {
        return this.tipoGarante;
    }
    
    public void setTipoGarante(String tipoGarante) {
        this.tipoGarante = tipoGarante;
    }
    public String getTipoMoneda() {
        return this.tipoMoneda;
    }
    
    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }




}


