package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1



/**
 * Mastertable generated by hbm2java
 */
public class Mastertable  implements java.io.Serializable {


     private Integer id;
     private int idTabla;
     private int idItem;
     private String denominacion;
     private String abreviatura;
     private boolean estado;

    public Mastertable() {
    }

    public Mastertable(int idTabla, int idItem, String denominacion, String abreviatura, boolean estado) {
       this.idTabla = idTabla;
       this.idItem = idItem;
       this.denominacion = denominacion;
       this.abreviatura = abreviatura;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdTabla() {
        return this.idTabla;
    }
    
    public void setIdTabla(int idTabla) {
        this.idTabla = idTabla;
    }
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


