package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1



/**
 * Operacion generated by hbm2java
 */
public class Operacion  implements java.io.Serializable {


     private Integer id;
     private Transaccion transaccion;
     private String denominacion;
     private String cuentacredito;
     private double agregado;
     private double pago;
     private double total;

    public Operacion() {
    }

    public Operacion(Transaccion transaccion, String denominacion, String cuentacredito, double agregado, double pago, double total) {
       this.transaccion = transaccion;
       this.denominacion = denominacion;
       this.cuentacredito = cuentacredito;
       this.agregado = agregado;
       this.pago = pago;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getCuentacredito() {
        return this.cuentacredito;
    }
    
    public void setCuentacredito(String cuentacredito) {
        this.cuentacredito = cuentacredito;
    }
    public double getAgregado() {
        return this.agregado;
    }
    
    public void setAgregado(double agregado) {
        this.agregado = agregado;
    }
    public double getPago() {
        return this.pago;
    }
    
    public void setPago(double pago) {
        this.pago = pago;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }




}


