package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1



/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private Integer id;
     private Rol rol;
     private Usuario usuario;

    public Permiso() {
    }

    public Permiso(Rol rol, Usuario usuario) {
       this.rol = rol;
       this.usuario = usuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


