package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1



/**
 * Personanatural generated by hbm2java
 */
public class Personanatural  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Persona persona;
     private String recibo;
     private boolean estado;

    public Personanatural() {
    }

	
    public Personanatural(Cliente cliente, Persona persona, boolean estado) {
        this.cliente = cliente;
        this.persona = persona;
        this.estado = estado;
    }
    public Personanatural(Cliente cliente, Persona persona, String recibo, boolean estado) {
       this.cliente = cliente;
       this.persona = persona;
       this.recibo = recibo;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getRecibo() {
        return this.recibo;
    }
    
    public void setRecibo(String recibo) {
        this.recibo = recibo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


