package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

    private Integer id;
    private Conyugue conyugue;
    private Estadocivil estadocivil;
    private Genero genero;
    private Integer dni;
    private String nombre;
    private String apellidoPat;
    private String apellidoMat;
    private String direccion;
    private String distrito;
    private String provincia;
    private String departamento;
    private String pais;
    private Long celular;
    private String email;
    private Long ruc;
    private Date fechaNacimiento;
    private String nacionalidad;
    private String profesion;

    public Persona() {
    }

    public Persona(int id) {
        this.id = id;
    }

    public Persona(Integer dni, String nombre, String apellidoPat, String apellidoMat, String direccion, Long celular) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.direccion = direccion;
        this.celular = celular;
    }

    public Persona(Estadocivil estadocivil, Genero genero, Integer dni, String nombre, String apellidoPat, String apellidoMat, String direccion, Long celular) {
        this.estadocivil = estadocivil;
        this.genero = genero;
        this.dni = dni;
        this.nombre = nombre;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.direccion = direccion;
        this.celular = celular;
    }

    public Persona(Conyugue conyugue, Estadocivil estadocivil, Genero genero, Integer dni, String nombre, String apellidoPat, String apellidoMat, String direccion, String distrito, String provincia, String departamento, String pais, Long celular, String email, Long ruc, Date fechaNacimiento, String nacionalidad, String profesion) {
        this.conyugue = conyugue;
        this.estadocivil = estadocivil;
        this.genero = genero;
        this.dni = dni;
        this.nombre = nombre;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.direccion = direccion;
        this.distrito = distrito;
        this.provincia = provincia;
        this.departamento = departamento;
        this.pais = pais;
        this.celular = celular;
        this.email = email;
        this.ruc = ruc;
        this.fechaNacimiento = fechaNacimiento;
        this.nacionalidad = nacionalidad;
        this.profesion = profesion;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Conyugue getConyugue() {
        return this.conyugue;
    }

    public void setConyugue(Conyugue conyugue) {
        this.conyugue = conyugue;
    }

    public Estadocivil getEstadocivil() {
        return estadocivil;
    }

    public void setEstadocivil(Estadocivil estadocivil) {
        this.estadocivil = estadocivil;
    }

    public Genero getGenero() {
        return genero;
    }

    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    public Integer getDni() {
        return this.dni;
    }

    public void setDni(Integer dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidoPat() {
        return this.apellidoPat;
    }

    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }

    public String getApellidoMat() {
        return this.apellidoMat;
    }

    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getDistrito() {
        return this.distrito;
    }

    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    public String getProvincia() {
        return this.provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    public String getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    public Long getCelular() {
        return this.celular;
    }

    public void setCelular(Long celular) {
        this.celular = celular;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getRuc() {
        return this.ruc;
    }

    public void setRuc(Long ruc) {
        this.ruc = ruc;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getNacionalidad() {
        return this.nacionalidad;
    }

    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    public String getProfesion() {
        return this.profesion;
    }

    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }

}
