package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Productocredito generated by hbm2java
 */
public class Productocredito implements java.io.Serializable {

    private Integer id;
    private Frecuenciapago frecuenciapago;
    private String codigo;
    private String nombre;
    private String descripcion;
    private double montoMinimo;
    private double montoMaximo;
    private double tasa;
    private int minPeriodoGracia;
    private int maxPeriodoGracia;
    private int minDiasPlazoPago;
    private int maxDiasPlazoPago;
    private double tem;
    private double centralRiesgo;
    private double encaje;
    private double tasaSeguroDesgravamen;
    private double comisionGastosAdm;
    private Date inicioFechaVigencia;
    private Date finFechaVigencia;
    private String docSustentatorios;
    private boolean estado;
    private int idTipoMoneda;
    private Integer idTipoGarantia;
    private int idTipoCredito;

    public Productocredito() {
    }

    public Productocredito(Frecuenciapago frecuenciapago, String codigo, String nombre, String descripcion, double montoMinimo, double montoMaximo, double tasa, int minPeriodoGracia, int maxPeriodoGracia, int minDiasPlazoPago, int maxDiasPlazoPago, double tem, double centralRiesgo, double encaje, double tasaSeguroDesgravamen, double comisionGastosAdm, Date inicioFechaVigencia, Date finFechaVigencia, String docSustentatorios, boolean estado, int idTipoMoneda, int idTipoCredito) {
        this.frecuenciapago = frecuenciapago;
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.montoMinimo = montoMinimo;
        this.montoMaximo = montoMaximo;
        this.tasa = tasa;
        this.minPeriodoGracia = minPeriodoGracia;
        this.maxPeriodoGracia = maxPeriodoGracia;
        this.minDiasPlazoPago = minDiasPlazoPago;
        this.maxDiasPlazoPago = maxDiasPlazoPago;
        this.tem = tem;
        this.centralRiesgo = centralRiesgo;
        this.encaje = encaje;
        this.tasaSeguroDesgravamen = tasaSeguroDesgravamen;
        this.comisionGastosAdm = comisionGastosAdm;
        this.inicioFechaVigencia = inicioFechaVigencia;
        this.finFechaVigencia = finFechaVigencia;
        this.docSustentatorios = docSustentatorios;
        this.estado = estado;
        this.idTipoMoneda = idTipoMoneda;
        this.idTipoCredito = idTipoCredito;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Frecuenciapago getFrecuenciapago() {
        return this.frecuenciapago;
    }

    public void setFrecuenciapago(Frecuenciapago frecuenciapago) {
        this.frecuenciapago = frecuenciapago;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public double getMontoMinimo() {
        return this.montoMinimo;
    }

    public void setMontoMinimo(double montoMinimo) {
        this.montoMinimo = montoMinimo;
    }

    public double getMontoMaximo() {
        return this.montoMaximo;
    }

    public void setMontoMaximo(double montoMaximo) {
        this.montoMaximo = montoMaximo;
    }

    public double getTasa() {
        return this.tasa;
    }

    public void setTasa(double tasa) {
        this.tasa = tasa;
    }

    public int getMinPeriodoGracia() {
        return this.minPeriodoGracia;
    }

    public void setMinPeriodoGracia(int minPeriodoGracia) {
        this.minPeriodoGracia = minPeriodoGracia;
    }

    public int getMaxPeriodoGracia() {
        return this.maxPeriodoGracia;
    }

    public void setMaxPeriodoGracia(int maxPeriodoGracia) {
        this.maxPeriodoGracia = maxPeriodoGracia;
    }

    public int getMinDiasPlazoPago() {
        return this.minDiasPlazoPago;
    }

    public void setMinDiasPlazoPago(int minDiasPlazoPago) {
        this.minDiasPlazoPago = minDiasPlazoPago;
    }

    public int getMaxDiasPlazoPago() {
        return this.maxDiasPlazoPago;
    }

    public void setMaxDiasPlazoPago(int maxDiasPlazoPago) {
        this.maxDiasPlazoPago = maxDiasPlazoPago;
    }

    public double getTem() {
        return this.tem;
    }

    public void setTem(double tem) {
        this.tem = tem;
    }

    public double getCentralRiesgo() {
        return this.centralRiesgo;
    }

    public void setCentralRiesgo(double centralRiesgo) {
        this.centralRiesgo = centralRiesgo;
    }

    public double getEncaje() {
        return this.encaje;
    }

    public void setEncaje(double encaje) {
        this.encaje = encaje;
    }

    public double getTasaSeguroDesgravamen() {
        return this.tasaSeguroDesgravamen;
    }

    public void setTasaSeguroDesgravamen(double tasaSeguroDesgravamen) {
        this.tasaSeguroDesgravamen = tasaSeguroDesgravamen;
    }

    public double getComisionGastosAdm() {
        return this.comisionGastosAdm;
    }

    public void setComisionGastosAdm(double comisionGastosAdm) {
        this.comisionGastosAdm = comisionGastosAdm;
    }

    public Date getInicioFechaVigencia() {
        return this.inicioFechaVigencia;
    }

    public void setInicioFechaVigencia(Date inicioFechaVigencia) {
        this.inicioFechaVigencia = inicioFechaVigencia;
    }

    public Date getFinFechaVigencia() {
        return this.finFechaVigencia;
    }

    public void setFinFechaVigencia(Date finFechaVigencia) {
        this.finFechaVigencia = finFechaVigencia;
    }

    public String getDocSustentatorios() {
        return this.docSustentatorios;
    }

    public void setDocSustentatorios(String docSustentatorios) {
        this.docSustentatorios = docSustentatorios;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getIdTipoMoneda() {
        return this.idTipoMoneda;
    }

    public void setIdTipoMoneda(int idTipoMoneda) {
        this.idTipoMoneda = idTipoMoneda;
    }

    public Integer getIdTipoGarantia() {
        return idTipoGarantia;
    }

    public void setIdTipoGarantia(Integer idTipoGarantia) {
        this.idTipoGarantia = idTipoGarantia;
    }

    public int getIdTipoCredito() {
        return this.idTipoCredito;
    }

    public void setIdTipoCredito(int idTipoCredito) {
        this.idTipoCredito = idTipoCredito;
    }

}
