package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer id;
     private Departamento departamento;
     private String nombre;
     private int reniec;
     private Set distritos = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(Departamento departamento, String nombre, int reniec) {
        this.departamento = departamento;
        this.nombre = nombre;
        this.reniec = reniec;
    }
    public Provincia(Departamento departamento, String nombre, int reniec, Set distritos) {
       this.departamento = departamento;
       this.nombre = nombre;
       this.reniec = reniec;
       this.distritos = distritos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getReniec() {
        return this.reniec;
    }
    
    public void setReniec(int reniec) {
        this.reniec = reniec;
    }
    public Set getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set distritos) {
        this.distritos = distritos;
    }




}


