package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registrocliente generated by hbm2java
 */
public class Registrocliente  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Usuario usuario;
     private Date fecha;

    public Registrocliente() {
    }

    public Registrocliente(Cliente cliente, Usuario usuario, Date fecha) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


