package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Representantelegal generated by hbm2java
 */
public class Representantelegal  implements java.io.Serializable {


     private Integer id;
     private Persona persona;
     private Personajuridica personajuridica;
     private String codigo;
     private String cargo;
     private Date fechaCreacion;

    public Representantelegal() {
    }

	
    public Representantelegal(Persona persona, Personajuridica personajuridica, String codigo, Date fechaCreacion) {
        this.persona = persona;
        this.personajuridica = personajuridica;
        this.codigo = codigo;
        this.fechaCreacion = fechaCreacion;
    }
    public Representantelegal(Persona persona, Personajuridica personajuridica, String codigo, String cargo, Date fechaCreacion) {
       this.persona = persona;
       this.personajuridica = personajuridica;
       this.codigo = codigo;
       this.cargo = cargo;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Personajuridica getPersonajuridica() {
        return this.personajuridica;
    }
    
    public void setPersonajuridica(Personajuridica personajuridica) {
        this.personajuridica = personajuridica;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


