package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipotransferencia generated by hbm2java
 */
public class Tipotransferencia implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private int estado;
    private Set transferencias = new HashSet(0);

    public Tipotransferencia() {
    }

    public Tipotransferencia(int id) {
        this.id = id;
    }

    public Tipotransferencia(String nombre, int estado) {
        this.nombre = nombre;
        this.estado = estado;
    }

    public Tipotransferencia(String nombre, int estado, Set transferencias) {
        this.nombre = nombre;
        this.estado = estado;
        this.transferencias = transferencias;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Set getTransferencias() {
        return this.transferencias;
    }

    public void setTransferencias(Set transferencias) {
        this.transferencias = transferencias;
    }

}
