package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

/**
 * Tipomoneda generated by hbm2java
 */
public class Tipomoneda implements java.io.Serializable {

    private Integer id;
    private String denominacion;
    private String codigo;
    private boolean estado;

    public Tipomoneda() {
    }

    public Tipomoneda(int id) {
        this.id = id;
    }

    public Tipomoneda(String denominacion, String codigo, boolean estado) {
        this.denominacion = denominacion;
        this.codigo = codigo;
        this.estado = estado;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

}
