package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transferencia generated by hbm2java
 */
public class Transferencia  implements java.io.Serializable {


     private Integer id;
     private Bobeda bobeda;
     private Cajero cajeroByIdCajero1;
     private Cajero cajeroByIdCajero2;
     private Tipotransferencia tipotransferencia;
     private Usuario usuario;
     private String motivo;
     private double monto;
     private Date fecha;
     private Set detallesaldotransferencias = new HashSet(0);

    public Transferencia() {
    }

	
    public Transferencia(Cajero cajeroByIdCajero1, Tipotransferencia tipotransferencia, Usuario usuario, String motivo, double monto, Date fecha) {
        this.cajeroByIdCajero1 = cajeroByIdCajero1;
        this.tipotransferencia = tipotransferencia;
        this.usuario = usuario;
        this.motivo = motivo;
        this.monto = monto;
        this.fecha = fecha;
    }
    public Transferencia(Bobeda bobeda, Cajero cajeroByIdCajero1, Cajero cajeroByIdCajero2, Tipotransferencia tipotransferencia, Usuario usuario, String motivo, double monto, Date fecha, Set detallesaldotransferencias) {
       this.bobeda = bobeda;
       this.cajeroByIdCajero1 = cajeroByIdCajero1;
       this.cajeroByIdCajero2 = cajeroByIdCajero2;
       this.tipotransferencia = tipotransferencia;
       this.usuario = usuario;
       this.motivo = motivo;
       this.monto = monto;
       this.fecha = fecha;
       this.detallesaldotransferencias = detallesaldotransferencias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bobeda getBobeda() {
        return this.bobeda;
    }
    
    public void setBobeda(Bobeda bobeda) {
        this.bobeda = bobeda;
    }
    public Cajero getCajeroByIdCajero1() {
        return this.cajeroByIdCajero1;
    }
    
    public void setCajeroByIdCajero1(Cajero cajeroByIdCajero1) {
        this.cajeroByIdCajero1 = cajeroByIdCajero1;
    }
    public Cajero getCajeroByIdCajero2() {
        return this.cajeroByIdCajero2;
    }
    
    public void setCajeroByIdCajero2(Cajero cajeroByIdCajero2) {
        this.cajeroByIdCajero2 = cajeroByIdCajero2;
    }
    public Tipotransferencia getTipotransferencia() {
        return this.tipotransferencia;
    }
    
    public void setTipotransferencia(Tipotransferencia tipotransferencia) {
        this.tipotransferencia = tipotransferencia;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetallesaldotransferencias() {
        return this.detallesaldotransferencias;
    }
    
    public void setDetallesaldotransferencias(Set detallesaldotransferencias) {
        this.detallesaldotransferencias = detallesaldotransferencias;
    }




}


