package com.polar.sisfinance.entity;
// Generated 04/07/2016 09:00:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion implements java.io.Serializable {

    private Integer id;
    private Cajero cajero;
    private Cliente cliente;
    private Tipotransaccion tipotransaccion;
    private String codigo;
    private String glosa;
    private Date fecha;
    private String nombrecliente;

    public Transaccion() {
    }

    public Transaccion(Cajero cajero, Cliente cliente, Tipotransaccion tipotransaccion, String codigo, Date fecha, String nombrecliente) {
        this.cajero = cajero;
        this.cliente = cliente;
        this.tipotransaccion = tipotransaccion;
        this.codigo = codigo;
        this.fecha = fecha;
        this.nombrecliente = nombrecliente;
    }

    public Transaccion(Cajero cajero, Cliente cliente, Tipotransaccion tipotransaccion, String codigo, String glosa, Date fecha, String nombrecliente) {
        this.cajero = cajero;
        this.cliente = cliente;
        this.tipotransaccion = tipotransaccion;
        this.codigo = codigo;
        this.glosa = glosa;
        this.fecha = fecha;
        this.nombrecliente = nombrecliente;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Cajero getCajero() {
        return this.cajero;
    }

    public void setCajero(Cajero cajero) {
        this.cajero = cajero;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Tipotransaccion getTipotransaccion() {
        return this.tipotransaccion;
    }

    public void setTipotransaccion(Tipotransaccion tipotransaccion) {
        this.tipotransaccion = tipotransaccion;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getGlosa() {
        return this.glosa;
    }

    public void setGlosa(String glosa) {
        this.glosa = glosa;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getNombrecliente() {
        return this.nombrecliente;
    }

    public void setNombrecliente(String nombrecliente) {
        this.nombrecliente = nombrecliente;
    }

}
